### PR TITLE
Pushing release v1.0 to production after bug fixes

### PR DESCRIPTION
**Pull request by iumairshuja**
Pushing release v1.0 to production after fixing some design issues on the homepage. These changes improve the look and feel, making the page more user-friendly. Ready to go live!

### CODE REVIEW

**Review by L1F21BSSE0122 — APPROVED** [review]
The code seems to be working fine, and there are no visible bug. Ready for production

**Review by farhan662 — APPROVED** [review]
Code is ready for production with main branch. Looks good and so bugs are visible.

**Review by SyedRazeeAbbasRizvi — APPROVED** [review]
The code is good to go. Main branch is ready for production

**Review by HassanJafery — APPROVED** [review]
well i have reviewed the fianl changes and it is good to go.

**Pull request merged**
